name: ruff
version: git
summary: An extremely fast Python linter, written in Rust.
# noinspection YAMLSchemaValidation
# https://youtrack.jetbrains.com/issue/PY-58754
description: |
  Ruff aims to be orders of magnitude faster than alternative tools while integrating more
  functionality behind a single, common interface.

  Ruff can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus a variety of plugins), [`isort`](https://pypi.org/project/isort/),
  [`pydocstyle`](https://pypi.org/project/pydocstyle/), [`yesqa`](https://github.com/asottile/yesqa),
  [`eradicate`](https://pypi.org/project/eradicate/), [`pyupgrade`](https://pypi.org/project/pyupgrade/),
  and [`autoflake`](https://pypi.org/project/autoflake/), all while executing tens or hundreds of
  times faster than any individual tool.

  Ruff goes beyond the responsibilities of a traditional linter, instead functioning as an advanced
  code transformation tool capable of upgrading type annotations, rewriting class definitions, sorting
  imports, and more.

confinement: strict
base: core22
# Performance difference with xz vs lzo is small in this case, but provides
# a ~40% reduction in file size for a very frequently updating snap.
compression: xz
contact: https://github.com/lengau/ruff/issues
issues:
  - https://github.com/lengau/ruff/issues
  - https://github.com/charliermarsh/ruff/issues
source-code: https://github.com/lengau/ruff
website: https://github.com/charliermarsh/ruff

parts:
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init
      chmod +x rustup-init
      ./rustup-init -y --no-modify-path --profile=minimal
  ruff:
    plugin: rust
    source: .
    after:
      - rust-deps
    build-environment:
      - CARGO_INSTALL_ROOT: "${CRAFT_PART_INSTALL}"
      - CARGO_BUILD_JOBS: "${CRAFT_PARALLEL_BUILD_COUNT}"
    rust-path:
      - ruff_cli
      - flake8_to_ruff
    override-build: |  # Override because we need to specify no-default-features
      cargo install --locked --path ruff_cli --force --no-default-features
      cargo install --locked --path flake8_to_ruff --force --no-default-features

apps:
  ruff:
    command: bin/ruff
    plugs:
      - home
  flake8-to-ruff:
    command: bin/flake8-to-ruff
    plugs:
      - home
