name: "[Snap] Release"

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGE_NAME: ruff
  PYTHON_VERSION: "3.7" # to build abi3 wheels
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  linux:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list-files.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - name: "Build snaps"
        uses: snapcore/action-build@v1
      - name: "Upload snap artifact"
        uses: actions/upload-artifact@v3
        with:
          name: snaps
          path: "*.snap"
      - name: "Generate snap publish matrix"
        id: list-files
        # Currently needed because of https://github.com/snapcore/action-publish/issues/22
        run: |
          echo "files="$(ls -1 *.snap | jq -cRs '. | split("\n") | map(if . != "" then . else empty end)') >> $GITHUB_OUTPUT

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - linux
    if: "startsWith(github.ref, 'refs/tags/')"
    strategy:
      matrix:
        file: ${{ fromJSON(needs.linux.outputs.files) }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: snaps
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAP_STORE_LOGIN }}
          snap: ${{ matrix.file }}
          release: candidate
